/**
 * Demo presets with realistic AI-generated JSON outputs.
 * Each includes common LLM repair challenges.
 */

export const demoPresets: Record<string, { label: string; desc: string; input: string; schema: string }> = {
  product: {
    label: 'Product Extraction',
    desc: 'E-commerce AI analysis with enrichment',
    input: `{
  "productId": "SKU-47291",
  "title": "Premium Wireless Noise-Canceling Headphones",
  "category": "Electronics > Audio",
  "price": "299.99",
  "currency": "USD",
  "rating": 4.7,
  "reviewCount": "1240",
  "inStock": "true",
  "specs": {
    "batteryLife": "30 hours",
    "weight": "250g",
    "drivers": "40mm",
    connectivity: ["Bluetooth 5.2", "3.5mm Jack"],  
    "waterproof": "IPX4",
  },
  "extractedFeatures": [
    "Active Noise Cancellation",
    "Comfort Fit",
    "Long Battery",
    "Wireless Connection",
  ],
  "sentiment": "positive",
  "avgReviewLength": 85.5,
  "commonComplaint": null,
  "marketAnalysis": {
    "competitors": "4",
    "pricePosition": "mid-premium",
    "demandTrend": "rising"
  },
  "recommendedPrice": $279.99,
  "buyersAlsoViewed": ["Case-001", "AuxCable-45"]
}`,
    schema: `z.object({
  productId: z.string(),
  title: z.string(),
  category: z.string(),
  price: z.number(),
  currency: z.string(),
  rating: z.number(),
  reviewCount: z.number(),
  inStock: z.boolean(),
  specs: z.object({
    batteryLife: z.string(),
    weight: z.string(),
    drivers: z.string(),
    connectivity: z.array(z.string()),
    waterproof: z.string(),
  }),
  extractedFeatures: z.array(z.string()),
  sentiment: z.enum(['positive', 'neutral', 'negative']),
  avgReviewLength: z.number(),
  commonComplaint: z.string().nullable(),
  marketAnalysis: z.object({
    competitors: z.number(),
    pricePosition: z.string(),
    demandTrend: z.string(),
  }),
  recommendedPrice: z.number(),
  buyersAlsoViewed: z.array(z.string()),
})`,
  },

  content: {
    label: 'Content Analysis',
    desc: 'Article summarization & metadata extraction',
    input: `{
  "url": "https://example.com/articles/ai-trends-2025",
  "headline": "Top 5 AI Trends Shaping 2025",
  "publishDate": "2025-03-11",
  "author": "Jane Chen",
  "wordCount": 3847,
  "readTime": "12",
  "category": ["Technology", "AI", "Trends"],
  "summary": "This article explores the five most significant AI trends expected to dominate 2025: multimodal models, edge AI, AI safety frameworks, enterprise integration, and constitutional AI. The piece emphasizes the shift toward practical, deployable solutions rather than research-only advances.",
  "keyTakeaways": [
    "Multimodal AI is becoming the standard for enterprise applications",
    "Edge inference is critical for latency-sensitive operations",
    "Safety and alignment are now table stakes for any serious AI deployment",
  ],
  "sentiment": "informative",
  "tone": "professional",
  "estimatedReach": "50000",
  "seoScore": "87",
  "suggestedTags": [multimodal, "edge-computing", "AI-safety", "2025-trends"],
  "relatedArticles": ["ai-alignment-guide", "edge-inference-benchmarks"],
  "engagement": {avgShareCount: "240", "avgCommentSentiment": "positive"},
  "confidenceScore": "0.94"
}`,
    schema: `z.object({
  url: z.string().url(),
  headline: z.string(),
  publishDate: z.string(),
  author: z.string(),
  wordCount: z.number(),
  readTime: z.number(),
  category: z.array(z.string()),
  summary: z.string(),
  keyTakeaways: z.array(z.string()),
  sentiment: z.string(),
  tone: z.string(),
  estimatedReach: z.number(),
  seoScore: z.number(),
  suggestedTags: z.array(z.string()),
  relatedArticles: z.array(z.string()),
  engagement: z.object({
    avgShareCount: z.number(),
    avgCommentSentiment: z.string(),
  }),
  confidenceScore: z.number().min(0).max(1),
})`,
  },

  entities: {
    label: 'Entity Extraction',
    desc: 'NLP: people, organizations, relationships',
    input: `{
  "sourceText": "Sarah Johnson from Acme Corp met with David Lee at OpenAI on March 10th to discuss partnership opportunities.",
  "entities": [
    {type: "PERSON", "value": "Sarah Johnson", "confidence": 0.98, "roles": ["executive"]},
    {type: "PERSON", "value": "David Lee", "confidence": "0.96", "roles": ["researcher"]},
    {type: "ORG", "value": "Acme Corp", "confidence": 0.99},
    {type: "ORG", "value": "OpenAI", "confidence": "0.98"},
    {type: "DATE", "value": "2025-03-10", "confidence": 0.95,},
  ],
  "relationships": [
    {subject: "Sarah Johnson", "predicate": "works_at", object: "Acme Corp"},
    {subject: "David Lee", "predicate": "works_at", "object": "OpenAI",},
    {subject: "Sarah Johnson", "predicate": "met_with", "object": "David Lee"},
  ],
  "extractedKeywords": ["partnership", "opportunities", "discussion",],
  "topicCluster": "business-development",
  "sentiment": "neutral",
  "language": "en",
  "qualityScore": "0.92"
}`,
    schema: `z.object({
  sourceText: z.string(),
  entities: z.array(z.object({
    type: z.string(),
    value: z.string(),
    confidence: z.number().min(0).max(1),
    roles: z.array(z.string()),
  })),
  relationships: z.array(z.object({
    subject: z.string(),
    predicate: z.string(),
    object: z.string(),
  })),
  extractedKeywords: z.array(z.string()),
  topicCluster: z.string(),
  sentiment: z.string(),
  language: z.string(),
  qualityScore: z.number().min(0).max(1),
})`,
  },

  code: {
    label: 'Code Analysis',
    desc: 'Function extraction, dependencies, metrics',
    input: `{
  "fileName": "utils/auth.ts",
  "functions": [
    {
      "name": "validateToken",
      "signature": "async function validateToken(token: string): Promise<boolean>",
      "lineStart": 5,
      "lineEnd": 18,
      "complexity": "3",
      "parameters": ["token"],
      "returnType": "Promise<boolean>",
      "isAsync": "true",
      "dependencies": ["jsonwebtoken", "config"],
    },
    {
      name: "refreshToken",
      "signature": "async function refreshToken(oldToken: string): Promise<string>",
      "lineStart": 20,
      "lineEnd": "35",
      "complexity": 4,
      "parameters": ["oldToken"],
      "returnType": "Promise<string>",
      "isAsync": true,
      "dependencies": ["validateToken", "crypto", "config",],
    }
  ],
  "imports": ["jsonwebtoken", "config", "crypto"],
  "cyclomaticComplexity": "7",
  "maintainabilityScore": "78",
  "testCoverage": "85"
}`,
    schema: `z.object({
  fileName: z.string(),
  functions: z.array(z.object({
    name: z.string(),
    signature: z.string(),
    lineStart: z.number(),
    lineEnd: z.number(),
    complexity: z.number(),
    parameters: z.array(z.string()),
    returnType: z.string(),
    isAsync: z.boolean(),
    dependencies: z.array(z.string()),
  })),
  imports: z.array(z.string()),
  cyclomaticComplexity: z.number(),
  maintainabilityScore: z.number(),
  testCoverage: z.number(),
})`,
  },

  chat: {
    label: 'Chat Classification',
    desc: 'Message intent, sentiment, priority routing',
    input: `{
  "messageId": "MSG-8472",
  "timestamp": "2025-03-11T10:45:00Z",
  "sender": "customer@example.com",
  "content": "I've been trying to reset my password for hours but keep getting an error code 403. This is really frustrating!",
  "intent": "support_request",
  "entities": {issue: "password_reset", errorCode: "403"},
  "sentiment": "negative",
  "urgency": "high",
  "priority": "2",
  "category": ["account", "error"],
  "suggestedResponse": "route_to_tier2_support",
  "confidence": "0.89",
  "escalationRequired": "true",
  "estimatedResolutionTime": "15 minutes",
  "suggestedSolution": "Clear browser cache and try incognito mode, Contact premium support if issue persists",
  "customerSatisfactionPrediction": "3.2"
}`,
    schema: `z.object({
  messageId: z.string(),
  timestamp: z.string(),
  sender: z.string().email(),
  content: z.string(),
  intent: z.string(),
  entities: z.object({
    issue: z.string(),
    errorCode: z.string(),
  }),
  sentiment: z.enum(['positive', 'neutral', 'negative']),
  urgency: z.enum(['low', 'medium', 'high', 'critical']),
  priority: z.number(),
  category: z.array(z.string()),
  suggestedResponse: z.string(),
  confidence: z.number().min(0).max(1),
  escalationRequired: z.boolean(),
  estimatedResolutionTime: z.string(),
  suggestedSolution: z.string(),
  customerSatisfactionPrediction: z.number(),
})`,
  },

  markdown: {
    label: 'Markdown Wrapper',
    desc: 'JSON wrapped in ```json fences',
    input: '```json\n{"name": "Alice", "age": 30}\n```',
    schema: `z.object({\n  name: z.string(),\n  age: z.number(),\n})`,
  },

  truncated: {
    label: 'Truncated Output',
    desc: 'Hit max_tokens mid-response',
    input: '{"users": [{"name": "Alice", "age": 30}, {"name": "Bob"',
    schema: `z.object({\n  users: z.array(z.object({\n    name: z.string(),\n    age: z.number().optional(),\n  })),\n})`,
  },
}
